version: '3'

services:

  app-service:
    build:
      context: .
    ports:
      - 5000:5000
    volumes:
      - ./src:/src:Z
    depends_on:
      - database
      - rabbitmq
    tty: true
    command: >
      sh -c 'flask run --host 0.0.0.0 --port 5000'
    networks:
      eye:
        ipv4_address: 172.18.0.8
    environment:
      - FLASK_ENV="development"
      - FLASK_APP=app
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://myuser:mypass@database:5432/eyedb
      - API_URL="http://localhost:5000/"
      - SERVER_NAME="localhost:5000"
      - INCLUDE_SCHEMAS=true
      - POOL_SIZE=30
      - POOL_TIMEOUT=15
      - TRACK_MODIFICATIONS=false
      - RECORD_QUERIES=true
      - SQLALCHEMY_ECHO=false
      - DEBUG=true
      - CELERY_BROKER_URL=amqp://brokeruser:brokerpass@rabbitmq//
      - CELERY_RESULT_BACKEND=amqp://brokeruser:brokerpass@rabbitmq//
  celery:
    build:
      context: .
      dockerfile: ./celeryworker.dockerfile
    command:
      [
        "celery",
        "-A",
        "src.celery_worker.celery_obj",
        "worker",
        "--loglevel=info",
      ]
    networks:
      eye:
        ipv4_address: 172.18.0.9
    depends_on:
      - database
      - rabbitmq
      - app-service
    tty: true
    environment:
      - DOCKER_CONFIG=True
      - PARTYOU_CONFIG=docker_config_local_no_pass
      - FLASK_ENV="development"
      - FLASK_APP=app
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://myuser:mypass@database:5432/eyedb
      - API_URL="http://localhost:5000/"
      - SERVER_NAME="localhost:5000"
      - INCLUDE_SCHEMAS=true
      - POOL_SIZE=30
      - POOL_TIMEOUT=15
      - TRACK_MODIFICATIONS=false
      - RECORD_QUERIES=true
      - SQLALCHEMY_ECHO=false
      - DEBUG=true
      - CELERY_BROKER_URL=amqp://brokeruser:brokerpass@rabbitmq//
      - CELERY_RESULT_BACKEND=amqp://brokeruser:brokerpass@rabbitmq//

  database:
    image: postgres:11
    restart: always
    ports:
      - 5432:5432
    networks:
      eye:
        ipv4_address: 172.18.0.3
    volumes:
      - "./postgres_restore:/restore"
      - "./postgres_data:/var/lib/postgresql/data/pgdata"
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypass
      - PGDATA=/var/lib/postgresql/data/pgdata

  rabbitmq:
    image: rabbitmq:3.7.15-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=brokeruser
      - RABBITMQ_DEFAULT_PASS=brokerpass
    networks:
      eye:
        ipv4_address: 172.18.0.2
    ports:
      - "5672:5672"
      - "15672:15672"


networks:
  eye:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
