[development]
SQLALCHEMY_DATABASE_URI = "postgresql://myuser:mypass@172.18.0.3/eyedb"
FLASK_APP="app"
API_URL="http://localhost:5000/"
SERVER_NAME="localhost:5000"
INCLUDE_SCHEMAS=true
POOL_SIZE=30
POOL_TIMEOUT=15
TRACK_MODIFICATIONS=false
RECORD_QUERIES=true
SQLALCHEMY_ECHO=false
DEBUG=true
CELERY_BROKER_URL='amqp://brokeruser:brokerpass@172.18.0.2//'
CELERY_RESULT_BACKEND='amqp://brokeruser:brokerpass@172.18.0.2//'

[testing]
API_URL="http://localhost:5000/"
SQLALCHEMY_DATABASE_URI = "postgresql://myuser:mypass@172.18.0.2/testdb"
CELERY_BROKER_URL='pyamqp://brokeruser:brokerpass@172.18.0.2//'
CELERY_RESULT_BACKEND='pyamqp://brokeruser:brokerpass@172.18.0.2//'
