[development]
DB_DSN_URI = "postgresql://partyoudbuser:partyou123@172.15.0.2/eyedb"
SQLALCHEMY_DATABASE_URI = "postgresql://partyoudbuser:partyou123@172.15.0.2/eyedb"
FLASK_APP="app"
API_URL="http://localhost:5000/"
SERVER_NAME="localhost:5000"
INCLUDE_SCHEMAS=true
POOL_SIZE=30
POOL_TIMEOUT=15
TRACK_MODIFICATIONS=false
RECORD_QUERIES=true
SQLALCHEMY_ECHO=false
DEBUG=true
CELERY_BROKER_URL='amqp://brokeruser:brokerpass@172.15.0.7//'
CELERY_RESULT_BACKEND='amqp://brokeruser:brokerpass@172.15.0.7//'

[testing]
API_URL="http://localhost:5000/"
SQLALCHEMY_DATABASE_URI = "postgresql://partyoudbuser:partyou123@172.15.0.2/testdb"
DB_DSN_URI = "postgresql://partyoudbuser:partyou123@172.15.0.2/testdb"
CELERY_BROKER_URL='pyamqp://brokeruser:brokerpass@172.15.0.7//'
CELERY_RESULT_BACKEND='pyamqp://brokeruser:brokerpass@172.15.0.7//'
