[development]
DB_DSN_URI = "postgresql://partyoudbuser:partyou123@172.15.0.2/eyedb"
SQLALCHEMY_DATABASE_URI = "postgresql://partyoudbuser:partyou123@172.15.0.2/eyedb"
FLASK_APP="app"
API_URL="http://localhost:5000/"
SERVER_NAME="localhost:5000"
URL_SCHEME="http"
SECRET_KEY="NOT_SECURE_SECRET_KEY"
USE_SIGNER=true
KEY_PREFIX="my_session_"
DBUSER="partyoudbuser"
DBPASS="partyou123"
DBNAME="communicationdb"
DBHOST="172.14.0.2"
DBPORT="5432"
INCLUDE_SCHEMAS=true
POOL_SIZE=30
POOL_TIMEOUT=15
TRACK_MODIFICATIONS=false
RECORD_QUERIES=true
SQLALCHEMY_ECHO=false
DEBUG=true

[testing]
API_URL="http://localhost:5000/"
SQLALCHEMY_DATABASE_URI = "postgresql://partyoudbuser:partyou123@172.15.0.2/testdb"
DB_DSN_URI = "postgresql://partyoudbuser:partyou123@172.15.0.2/testdb"
